# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b8860b3a4dcab6cd2f9e63ad7792c8588e960053285c5cd2673587562bee77c4ca8920b49364f8f30a323e54c38c0c9bde8c9857ca3f0cfe6ca42cb282f5fcd

test:
  secret_key_base: 044f5d169fa6d82eaca35fa622e47f944f2e5a92359737ea4e443db8a97d3c1fbe07fde059f2b95832f443791e1d6ac90253eba2a7cfdad0a75094e10297df3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
